DROP TABLE SEL_UPDATES;
DROP TABLE SEL_READINGS;
DROP TABLE SEL_ALARMS;
DROP TABLE SEL_REQUESTS;
DROP TABLE SEL_OUTPUTS;
DROP TABLE SEL_MEASURE_UNITS;
DROP TABLE SEL_TYPES;
DROP TABLE SEL_STATUSES;
DROP TABLE SEL_MODES;
DROP TABLE SEL_UNITS;
DROP TABLE SEL_SENSORS;
GO