DROP TABLE MONNIT_SENSOR_VOLTAGE;
DROP TABLE MONNIT_PENDING_CHANGES;
DROP TABLE MONNIT_BATTERY_STATUS;
DROP TABLE MONNIT_SIGNAL_STATUS;
DROP TABLE MONNIT_READINGS;
DROP TABLE MONNIT_DATA_TYPES;
DROP TABLE MONNIT_PLOT_LABELS;
DROP TABLE MONNIT_SENSORS;
DROP TABLE MONNIT_NETWORKS;
DROP TABLE MONNIT_APPLICATIONS;
GO