/* Drop existing TTN tables from the DB */ 
DROP TABLE TTN_UPLINK_SETTINGS
DROP TABLE TTN_READINGS
DROP TABLE TTN_UPLINK_TOKENS
DROP TABLE TTN_CORRELATION_IDS
DROP TABLE TTN_DATETIMES
DROP TABLE TTN_HOPS
DROP TABLE TTN_RX
DROP TABLE TTN_UPLINKS
DROP TABLE TTN_DEVICES
DROP TABLE TTN_SENSORS
DROP TABLE TTN_GATEWAYS
DROP TABLE TTN_LOCATIONS
DROP TABLE TTN_WARNINGS
DROP TABLE TTN_APPLICATIONS
GO
